In [2]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.7.0+cu126


In [4]:
scalar = torch.tensor(7)
print(scalar)
scalar.ndim

tensor(7)


0

In [5]:
vector = torch.tensor([7,7,7])
print(vector)
vector.ndim
vector.shape

tensor([7, 7, 7])


torch.Size([3])

In [6]:
random_tensor = torch.rand(10, 3,4)
random_tensor

tensor([[[0.0206, 0.5300, 0.3062, 0.7693],
         [0.5189, 0.6824, 0.2451, 0.2126],
         [0.1265, 0.5992, 0.4306, 0.0388]],

        [[0.7489, 0.9616, 0.9069, 0.9178],
         [0.5250, 0.1058, 0.1506, 0.2769],
         [0.7802, 0.4349, 0.9836, 0.8979]],

        [[0.4931, 0.2786, 0.6984, 0.6268],
         [0.1196, 0.6225, 0.5827, 0.7062],
         [0.5808, 0.4771, 0.3788, 0.5337]],

        [[0.9012, 0.0803, 0.1311, 0.4591],
         [0.5282, 0.2819, 0.2052, 0.2041],
         [0.8803, 0.1705, 0.9415, 0.1592]],

        [[0.5361, 0.1876, 0.9387, 0.5233],
         [0.5299, 0.1194, 0.1946, 0.0957],
         [0.9059, 0.1888, 0.4890, 0.8755]],

        [[0.9206, 0.9628, 0.0782, 0.4791],
         [0.2790, 0.5892, 0.2581, 0.6715],
         [0.0942, 0.1927, 0.5201, 0.6984]],

        [[0.6270, 0.0465, 0.8981, 0.2362],
         [0.2591, 0.4711, 0.7336, 0.1690],
         [0.7364, 0.4622, 0.2802, 0.7203]],

        [[0.0130, 0.5340, 0.3413, 0.4999],
         [0.1208, 0.3085, 0.5014, 0.7896

In [7]:
random_tensor.ndim

3

In [8]:
img_shape = torch.rand(size=(224, 224, 3))
img_shape.shape

torch.Size([224, 224, 3])

In [9]:
zero = torch.zeros(size=(3,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
torch.range(2,20)
t0 = torch.arange(start=2, end=20, step=6)
zeros = torch.zeros_like(input=t0)
zeros

/tmp/ipykernel_4825/3848811159.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2,20)


tensor([0, 0, 0])

In [12]:
float_32 = torch.tensor([3.0,9.0, 89.0],
                        dtype= None)
float_32.dtype

torch.float32

In [13]:
float_32 = torch.tensor([3.0,9.0, 89.0],
                        dtype= torch.float16)
float_32.dtype

torch.float16

In [14]:
float_32 = torch.tensor([3.0,9.0, 89.0],
                        dtype= None, 
                        device="cuda",
                        requires_grad=False)
float_32.dtype

torch.float32

In [15]:
float_16 = float_32.type(torch.float16)
float_16

tensor([ 3.,  9., 89.], device='cuda:0', dtype=torch.float16)

In [16]:
float_16*float_32

tensor([   9.,   81., 7921.], device='cuda:0')

In [17]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3751, 0.4108, 0.2080, 0.1278],
        [0.1916, 0.4097, 0.7261, 0.2292],
        [0.9786, 0.4558, 0.4869, 0.2108]])

In [18]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Sahpe : {some_tensor.shape}")
print(f"Device : {some_tensor.device}")

tensor([[0.3751, 0.4108, 0.2080, 0.1278],
        [0.1916, 0.4097, 0.7261, 0.2292],
        [0.9786, 0.4558, 0.4869, 0.2108]])
Datatype of tensor : torch.float32
Sahpe : torch.Size([3, 4])
Device : cpu


2 hours 11 minutes

In [19]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [20]:
tensor*10

tensor([10, 20, 30])

In [21]:
tensor-10

tensor([-9, -8, -7])

In [22]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [23]:
torch.add(tensor, 50)

tensor([51, 52, 53])

In [24]:
tensor*tensor

tensor([1, 4, 9])

In [25]:
torch.matmul(tensor, tensor)

tensor(14)

In [26]:
t1 = torch.tensor([[3,4,8],
                   [2,4,9],
                   [4,5,-5]])
t1*t1

tensor([[ 9, 16, 64],
        [ 4, 16, 81],
        [16, 25, 25]])

In [27]:
torch.matmul(t1,t1)

tensor([[ 49,  68,  20],
        [ 50,  69,   7],
        [  2,  11, 102]])

2 hours 28 minuts

In [28]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))
#given the error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [29]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))


tensor([[0.8431, 0.4889, 0.7058],
        [0.8145, 0.3854, 0.8341],
        [0.5914, 0.3660, 0.4546]])

In [30]:
torch.matmul(torch.rand(5,4), torch.rand(4,10)).shape

torch.Size([5, 10])

In [31]:
A = torch.rand(2,4)
A, A.shape

(tensor([[0.0518, 0.1257, 0.8445, 0.0274],
         [0.2733, 0.1328, 0.2530, 0.5321]]),
 torch.Size([2, 4]))

In [ ]:
A.T, A.T.shape

(tensor([[0.7192, 0.2495],
         [0.2326, 0.7201],
         [0.5936, 0.9541],
         [0.8300, 0.8432]]),
 torch.Size([4, 2]))

Find min, max, sum

In [ ]:
x = torch.arange(2, 100, 10)
x.dtype

torch.int64

In [ ]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(2), tensor(92), tensor(47.), tensor(470))

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

3 hours

In [32]:
import torch
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [33]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [34]:
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [35]:
x_reshape = x.reshape(5,2)
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

Completed 3 hours 10 minutes

In [36]:
x_stack = torch.stack([x,x,x,x],dim=0)
x_stack

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [38]:
x_reshape.shape

torch.Size([5, 2])

In [39]:
x_reshape.squeeze().shape

torch.Size([5, 2])

In [41]:
x = torch.arange(1,10,1)
x.shape

torch.Size([9])

In [43]:
x_reshape = x.reshape(1,9)
x_reshape.shape

torch.Size([1, 9])

In [45]:
x_squeez = x_reshape.squeeze()
x_squeez.shape

torch.Size([9])

In [ ]:
x_unsquzed = x_squeez.unsqueeze(dim=0)
x_unsquzed.shape

torch.Size([9, 1])

In [54]:
x = torch.randn(2,3,5)
x

tensor([[[ 0.1565,  0.5530, -2.0854,  0.6807, -0.3563],
         [-0.5485,  0.4276, -0.0517, -0.8266, -1.5075],
         [ 1.1500,  0.7877,  1.5423, -1.1795, -0.4177]],

        [[-0.8461,  0.8306,  0.3287,  0.6973,  1.8499],
         [ 0.6785, -0.8331, -0.1438,  0.6121, -0.5927],
         [ 1.8612,  0.9313,  1.4913,  1.4599, -1.4078]]])

In [55]:
x_originl = torch.rand(size=(224,224,3))
x_permu = x_originl.permute(2,0,1)
print(f"Previous : {x_originl.shape}")
print(f"New : {x_permu.shape}")

Previous : torch.Size([224, 224, 3])
New : torch.Size([3, 224, 224])


3 hours 24 minutes

In [58]:
import torch

In [59]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
x[0,0],x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [65]:
x[0][2][0]

tensor(7)

In [66]:
x[:,0]

tensor([[1, 2, 3]])

In [67]:
x[:,:,2]

tensor([[3, 6, 9]])

In [68]:
import torch
import numpy as np

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [73]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [74]:
tensor = torch.ones(7)
num_ten = tensor.numpy()
tensor, num_ten

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
num_ten.dtype

dtype('float32')

3 hours 42 min
Reduce randomness
torch.rand

In [80]:
import torch

In [82]:
ra = torch.rand(3,3)
rb = torch.rand(3,3)
print(ra)
print(rb)
print(ra==rb)

tensor([[0.0212, 0.7924, 0.7187],
        [0.4196, 0.3194, 0.9104],
        [0.9140, 0.4850, 0.1749]])
tensor([[0.6863, 0.7445, 0.1451],
        [0.8355, 0.3217, 0.1869],
        [0.6086, 0.0116, 0.3670]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [86]:

RANDOM_SEED = 77
torch.manual_seed(RANDOM_SEED)
rc = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rd = torch.rand(3,4)

print(rc)
print(rd)
print(rc==rd)


tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


GPU
3:53:0
agonstic

In [87]:
import torch
torch.cuda.is_available()

True

In [88]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [89]:
torch.cuda.device_count()

1

Putting tensors(or models) on gpu

In [90]:
tensor = torch.tensor([1,3,4], device="cpu")
print(tensor, tensor.device)

tensor([1, 3, 4]) cpu


In [91]:
#move to gpu
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 3, 4], device='cuda:0')

In [92]:
#back to cpu
tensor_to_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [93]:
back_cpu = tensor_to_gpu.cpu().numpy()
back_cpu

array([1, 3, 4])

Excersises
4:13:0